import type { TNinjaData } from "./types";

export enum ECategory {
  currency = 'Currency',
  fragments = 'Fragment',
  invitations = 'Invitation',
  delirium_orbs = 'DeliriumOrb',
  watchstones = 'Watchstone',
  oils = 'Oil',
  incubators = 'Incubator',
  scarabs = 'Scarab',
  fossils = 'Fossil',
  resonators = 'Resonator',
  essences = 'Essence',
  cards = 'DivinationCard',
  artifacts = 'Artifact',
  prophecies = 'Prophecy',
  gems = 'SkillGem',
  base_types = 'BaseType',
  enchants = 'HelmetEnchant',
  unique_maps = 'UniqueMap',
  maps = 'Map',
  unique_jewels = 'UniqueJewel',
  unique_flasks = 'UniqueFlask',
  unique_weapons = 'UniqueWeapon',
  unique_armours = 'UniqueArmour',
  unique_accessories = 'UniqueAccessory',
  beasts = 'Beast',
  vials = 'Vial',
  blight_ravaged_maps = 'BlightRavagedMap',
  blighted_maps = 'BlightedMap',
}

export const CATEGORIES = [
  ECategory.currency,
  ECategory.fragments,
  ECategory.cards,
  ECategory.artifacts,
  // ECategories.prophecy,
  ECategory.oils,
  ECategory.incubators,
  ECategory.unique_weapons,
  ECategory.unique_armours,
  ECategory.unique_accessories,
  ECategory.unique_flasks,
  ECategory.unique_jewels,
  ECategory.gems,
  ECategory.maps,
  ECategory.blighted_maps,
  ECategory.blight_ravaged_maps,
  ECategory.unique_maps,
  ECategory.delirium_orbs,
  ECategory.invitations,
  ECategory.scarabs,
  // ECategories.watchstone,
  // ECategories.basetype,
  ECategory.fossils,
  ECategory.resonators,
  ECategory.enchants,
  ECategory.beasts,
  ECategory.essences,
  ECategory.vials,
]

export const INITIAL_NINJA_DATA_STATE: TNinjaData = {
  data: null,
  icons: null,
  loading: false,
  error: '',
}
